### ISSUE TITLE
revamp the README.MD of the project

### ISSUE THREAD

**Issue by benderyRAF** [benderyRAF/WPF_Chromium#9]
revamp the README.MD to contain full instructions about how to set up the project

**Comment by benderyRAF** [comment]
done in commit [de0c835](https://github.com/benderyRAF/WPF_Chromium/commit/de0c835fee9ce1cb4b8a5e5d97c19cecebfe8a2d)

**Comment by benderyRAF** [comment]
only 2/3 parts finished

**Comment by Itamar188** [comment]
done.
